services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    environment:
      APP_ENV: production
      APP_PORT: ${APP_PORT}

      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_TTL_PRICE: ${REDIS_TTL_PRICE}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH_EXPIRATION_TIME: ${JWT_REFRESH_EXPIRATION_TIME}

      CRYPTO_PRICE_API: ${CRYPTO_PRICE_API}
      CRYPTO_PRICE_API_KEY: ${CRYPTO_PRICE_API_KEY}
      STOCK_PRICE_API: ${STOCK_PRICE_API}

      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS}

      RATE_LIMIT_TTL: ${RATE_LIMIT_TTL}
      RATE_LIMIT_LIMIT: ${RATE_LIMIT_LIMIT}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

    networks:
      - dokploy-network

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.monity-api.rule=Host(`api-assetmonitor.my.id`)"
      - "traefik.http.routers.monity-api.entrypoints=websecure"
      - "traefik.http.routers.monity-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.monity-api.loadbalancer.server.port=${APP_PORT}"

networks:
  dokploy-network:
    external: true
